### ISSUE TITLE
생년월일 디폴트 값 수정

### ISSUE THREAD

**Issue by engolder** [Jaws-bar/Entry3.0-EntrySystem#170]
2002 -> 2003
대부분의 학생이 2003년생이다

**Comment by SayBGM** [comment]
회원가입할 때 지정되는 데이터가 몇가지 있습니다.
인적사항이나 전형구분 등등.
문제인건 회원가입한 학생들이 2002-01-01로 서버에서 받아오기 때문에 생긴 문제로 판단되어 서버에서의 수정이 필요해보입니다.
![image](https://user-images.githubusercontent.com/28648915/46929481-d270de80-d07a-11e8-950c-74484c6aec45.png)
