### ISSUE TITLE
메인페이지 플로우 개선

### ISSUE THREAD

**Issue by engolder** [Jaws-bar/Entry3.0-EntrySystem#175]
본인인증, 원서작성, 원서수정 등의 단어와 전체 흐름 개선이 필요해보임

**Comment by SayBGM** [comment]
원서작성 버튼을 누르면 
처음 | 이어서 라는 모달이 나옴

처음 누르면 = /auth
이어서 누르면 login 모달 나오고 => /mypage

모달 작업은 제가 할게요

**Comment by rscarrera27** [comment]
#185
