### ISSUE TITLE
검증 모달 ux

### ISSUE THREAD

**Issue by engolder** [Jaws-bar/Entry3.0-EntrySystem#178]
어떠한 기능(미작성 페이지 알려주고 이동하는 기능)을 하는지 사용자가 한눈에 의식하기 어려움,
마우스 호버시 애니메이션 z-index 이상함

**Comment by rscarrera27** [comment]
이건 어떻게 됬어요? 이거 호버해서 해야한다는거 어렵게 느끼는 애들 많긴 하더라구요

**Comment by SayBGM** [comment]
노-답임 이건 ㄹㅇ 우짤수가 없당께요
