### ISSUE TITLE
모든 form의 인풋에서 값 체크

### ISSUE THREAD

**Issue by rscarrera27** [Jaws-bar/Entry3.0-EntrySystem#179]

**Comment by rscarrera27** [comment]
#172

**Comment by SayBGM** [comment]
이메일 정규식 뭘쓰던가에 오류 오지게뜸;;; 지금은 서버에 있는 정규식 쓰고 있음

**Comment by rscarrera27** [comment]
수정해야 할 것들은 
인풋 자릿수 제한, 숫자필드에 한글 입력, 특수기호 차단 이상한 값은 체크 후 아예 서버에 안보내는 형식으로(ex: 전화번호 6자리일 경우 전화번호는 아예 비우고 보내기)

**Comment by rscarrera27** [comment]
그래서 이거 어떻게 됬나요 @SayBGM, @Pewww
